version: '3'
services:
  database:
    image: postgres:15
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: directus
      POSTGRES_PASSWORD: password
      POSTGRES_DB: directus

  directus:
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      # This maps your local folders to the container so you can share code
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
      - ./scripts:/directus/scripts
    environment:
      KEY: 'a-random-secure-string-for-your-project'
      SECRET: 'another-random-secure-string'
      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'password'
      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'password'
      EXTENSIONS_AUTO_RELOAD: true
    depends_on:
      - database

volumes:
  data:
